controller_list:
  - name: slim/arm_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_roll_joint
      - elbow_pitch_joint
      - wrist_roll_joint
      - wrist_pitch_joint
      - gripper_roll_joint
  - name: slim/gantry_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - fl_lift_joint
      - slide_rail_base_joint
  - name: slim/gripper_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger_joint
      - r_gripper_aft_joint
      - l_gripper_fwd_joint
      - r_gripper_fwd_joint
      - r_gripper_aft_pincher_joint
      # - gripper_finger_pincher_joint
  - name: slim/gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - gripper_finger_pincher_joint
