arm_controller:
  type: "position_controller/JointTrajectoryController"
  joints:
    - shoulder_pan_joint
    - shoulder_pitch_joint
    - elbow_roll_joint
    - elbow_pitch_joint
    - wrist_roll_joint
    - wrist_pitch_joint
    - gripper_roll_joint
gantry_controller:
  type: "position_controller/JointTrajectoryController"
  joints:
    - fl_lift_joint
    - slide_rail_base_joint
gripper_controller:
  type: "position_controller/JointTrajectoryController"
  joints:
    - gripper_finger_joint
    - r_gripper_aft_joint
    - l_gripper_fwd_joint
    - r_gripper_fwd_joint
    - gripper_finger_pincher_joint
    - r_gripper_aft_pincher_joint
    
    