controller_manager_ns: clam_controller_manager
controller_list:
  - name: clam_trajectory_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_pan_joint
      - gripper_roll_joint
      - shoulder_pitch_joint
      - elbow_roll_joint
      - elbow_pitch_joint
      - wrist_roll_joint
      - wrist_pitch_joint
  - name: clam_gripper_controller
    ns: gripper_action
    default: true
    joints:
      - gripper_finger_joint